using UnityEngine;

[CreateAssetMenu(
    fileName = nameof(MovementAI),
    menuName = "Movement/" + AssetMenuNamingConventions.HOOK + 
               "/" + AssetMenuNamingConventions.HOOK + 
               "s/" + nameof(MovementAI),
    order = 1
)]
public class MovementAI : MovementHooks
{
    [SerializeField] protected MovementStrategy m_DirectionStrategy;

    /// <summary>
    /// Returns the direction generated by the connected strategy.
    /// </summary>
    /// <param name="requester">The Transform of the GameObject requesting the direction.</param>
    /// <param name="target">The target Transform of the requester.</param>
    /// <returns></returns>
    public override Vector2 ComputeDirection(Transform requester = null, Transform target = null)
    {
        return this.m_DirectionStrategy.ComputeDirection(requester, target);
    }
}
